 # Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'MyOwnWorkout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyOwnWorkout
  pod 'KeychainSwift', '~> 20.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
end
